# =======================
# Configuration to expose Redis Pod (Internal Only)
# =======================
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: hwwai
spec:
  type: NodePort
  selector:
    app: hwwai
    tier: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30008	# [30000,32767]

---
# =======================
# Configuration for storage
# =======================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: hwwai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# =======================
# Configuration for Redis Deployment
# =======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: hwwai
spec:
  replicas: 1  # One instance is enough for cache
  selector:
    matchLabels:
      app: hwwai
      tier: redis
  template:
    metadata:
      labels:
        app: hwwai
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/data"
              name: redis-storage
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim # Mount to Persistent Service Claim